boomer1_score_methods = {
0:"score as groundstroke",
1:"score as volley",
2:"no scoring",
3:"score as overhead",
4:"score as passing shot",
5:"deuce court",
6:"ad court",
7:"backhand third of court",
8:"center third of court",
9:"forehand third",
10:"deep deuce court",
11:"deep ad court",
12:"short deuce court",
13:"short ad court",
14:"lob deep and high",
15:"volley out of center third",
16:"volley deuce court",
17:"volley ad court",
18:"volley backhand third",
19:"volley center third",
20:"volley forehand third",
21:"deep deuce court",
22:"deep ad court",
23:"volley short very wide Deuce court",
24:"volley short very wide Ad court",
25:"Ad court 50+",
26:"Ad court 55+",
27:"Ad court 60+",
28:"Ad court 65+",
29:"Deuce court 50+",
30:"Deuce court 55+",
31:"Deuce court 60+",
32:"Deuce court 65+",
33:"Deep Ad court 50+",
34:"Deep Ad court 55+",
35:"Deep Ad court 60+",
36:"Deep Ad court 65+",
37:"Deep Deuce court 50+",
38:"Deep Deuce court 55+",
39:"Deep Deuce court 60+",
40:"Deep Deuce court 65+",
41:"Very Deep Deuce court, within 9 feet of baseline",
42:"Very Deep Ad court, within 9 feet of baseline",
43:"Deep",
44:"Very Deep",
45:"Overhead out of center third",
46:"Overhead deuce court",
47:"Overhead ad court",
48:"Overhead backhand third",
49:"Overhead center third",
50:"Overhead forehand third",
51:"Serve Deuce Wide",
52:"Serve Deuce T",
53:"Serve Ad T",
54:"Serve Ad Wide",
55:"Drop shot",
56:"Serve Deuce court",
57:"Serve Ad court",
58:"singles court",
59:"deeper than service line, middle 1/3 of court"
}