# makes lists for shottype and rotary lookups
from drill_file_defines import *

BALL_CFG_LABELS = [SHOTTYPE_DF, LEVEL_DF, ROTARY_TYPE_DF, SCORE_METHOD_DF, DELAY_DF,\
   SPEED_DF, SPIN_DF , ELEVATION_DF, AUDIO_DF]


SHOTTYPE_NAME_LIST = [ \
SERVE_NAME_SHOTTYPE, \
DROP_NAME_SHOTTYPE, \
FLAT_NAME_SHOTTYPE, \
HEAVY_NAME_SHOTTYPE, \
CHIP_NAME_SHOTTYPE, \
LOB_NAME_SHOTTYPE, \
TOPSPIN_NAME_SHOTTYPE, \
PASS_NAME_SHOTTYPE, \
NONE_NAME_SHOTTYPE, \
CUSTOM_NAME_SHOTTYPE, \
RAND_GROUND_NAME_SHOTTYPE, \
RAND_NET_NAME_SHOTTYPE, \
]

SHOTTYPE_VALUE_LIST = [0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44] 
